### PR TITLE
Support negative temperatures

### PR DESCRIPTION
**Pull request by doldis77**
Added ability to show negative values, mostly needed in scandinavia during the winter-season =)

### CODE REVIEW

**Comment by bauer-andreas** [comment]
That's definitely a valid concern 😅 

However your implementation is not the best approach since your changing the Temperature characteristic globally for every plugin. Would be better to create a new one. Do you want to change your implementation or should I just implement it myself?

Thanks for the PR though

**Comment by doldis77** [comment]
You can do it ;) I just noticed the lack of negative values. Didn't think it through "all the way"

**Comment by bauer-andreas** [comment]
Okay sorry, my bad, your approach was perfectly fine 😅 I did confuse some things

**Comment by bauer-andreas** [comment]
v0.1.7 is live

**Pull request merged**
